### ISSUE TITLE
USER STORY: User requiring Care - Delete their account

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#11]
As a **Logged in User**, I can **delete my Account** so that **I can easily manage my content**

**Acceptance Criteria**
- Delete:
  - A logged in user will see a Delete Account button on Accounts they created
  - On clicking the button, they will be asked if they are sure they wish to Delete (to avoid accidental deletion)
  - The user will receive a message to show the deletion was a success

**Tasks**
 - [ ] Create Delete Class in views.py.
 - [ ] Ensure only logged in Users can delete an Account that they created.
 - [ ] Create a delete buttons in Account Detail template and only display if user is authenticated and is the creator of the Account.
 - [ ] Create delete Article html templates
 - [ ] Wire up URLs to render templates
 - [ ] Create success messages for a successful Deletion
