### ISSUE TITLE
USER STORY: Care Provider - create new account

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#14]
As a **Care Provider** I can **create an account** so that I can **add my information and contact details**

**Acceptance Criteria**
- Signup button is easy to see and is on the homepage
- Signup button navigates to a signup page
- Signup page is easy to complete, and data is validated
- When signup details are complete, a click submit will create a new account
- When the new account is created, I am notified that the account creation was successful

**Tasks**
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
- [ ] Add signup link to navbar and to the home page
- [ ] Customise allauth signup form HTML template
- [ ] Create message to notify user of successfully creating a new account
