### ISSUE TITLE
USER STORY: Care Provider Login or Logout

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#15]
As a **Registered Care Provider**, I can **log in or log out of my account** so that **I can keep my account secure**

**Acceptance Criteria - user is logged out**
- Sign in button is easily viewable on the home page and on navigation 
- Clicking the Sign in button brings the user to the Sign in page
- When I fill in the correct details, the user will be logged in and receive a message to let me know I was successful
- If incorrect details are entered, the user will receive a message telling me what field I have entered incorrectly and what they should do to correctly login

**Acceptance Criteria - when user is logged in**
- When I click the logout button the user will be asked to confirm I wish to logout
- On confirmation, the user will receive a message to say logout was successful

**Tasks**

- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
- [ ] Add log in and log out links to the navigation bar
- [ ] Customise allauth login and logout HTML template
- [ ] Create messages for: successful login/logout, incorrect login details
