### ISSUE TITLE
USER STORY: Care Provider - Delete account

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#18]
As a **Registered Care Provider**, I can **delete my Account** so that **I can easily delete my content**

**Acceptance Criteria**
- Delete:
  - A logged in user will see a Delete Account button on Account that they created
  - On clicking the button, they will be asked if they are sure they wish to Delete (to avoid accidental deletion)
  - The user will receive a message to show the deletion was a success

**Tasks**
 - [ ] Create Delete Classe in views.py.
 - [ ] Ensure only logged in Users can delete articles that they created.
 - [ ] Create a delete buttons in Account Detail template and only display if user is authenticated and is the creator of the Account.
 - [ ] Create delete Account html templates
 - [ ] Wire up URLs to render templates
 - [ ] Create success messages for a successful Deletion
