### ISSUE TITLE
USER STORY: Site Navigation

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#3]
As a **Site User**, I can **intuitively navigate the site** so that **I can easily find the content I require**

**Acceptance Criteria**
- The navigation bar is clearly visible on all pages of the site, and the text on the links make it clear to the user where the link brings them
- The navigation bar changes on rollover to show where the user is about to click
- The navigation bar shows the user what page they are currently on
- The navigation bar collapses to a burger menu on smaller screens

**Tasks**
- [ ] Create navigation bar
- [ ] Create easy to view rollover and current page design
- [ ] Create burger menu icon
