### ISSUE TITLE
USER STORY: View a list of care providers with pagination

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#4]
As a **Site User**, I can **view a paginated list of Care Providers** so that I can **view and browse a list of Care Providers**

**Acceptance Criteria**
- On the main articles page the user can see a list view of each care provider with summary information (speciality field, contact information etc)
- The user can clearly see what each care provider provides
- When the user clicks on a care provider, they get a full view of all of the care provider's details

**Tasks**
- [ ]  Create a Care Provider class in views.py to show a list view of the Care Providers
 - [ ]  Create a browse HTML template
- [ ]   Create a layout that is both responsive and easy to view the basic information of each Care Provider
- [ ]   Link the Summary Care Provider to the Full Care Provider's details
 - [ ]  Add pagination
