### ISSUE TITLE
USER STORY: View care providers full profile

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#5]
As a **Site User**, I can **click on a Care Provider on the list view** so that I can **view the full version of the Care Provider's details, and view ratings and comments left by users**

**Acceptance Criteria**
- on clicking a Care Provider the user is brought to the Full Care Providers details view
- the Care Provider information is clearly displayed
- the user can view ratings and comments left by users

**Task**
- [ ] Link Care Provider to full Care Provider view
- [ ] Make full Care Provider's details easy to read and responsive
- [ ] Show ratings and comments left by users on page
