### ISSUE TITLE
USER STORY: User Requiring Care - Create a new Account

### ISSUE THREAD

**Issue by RozWelch** [RozWelch/CareHub-Project4-2023#6]
Ad a **Frequent User** I can **create a new account** so that I can **access all functions provided by the app**

**Acceptance Criteria**
- Signup button is easy to see and is on the homepage
- Signup button navigates to a signup page
- Signup page is easy to complete, and data is validated
- When signup details are complete, a click submit button will create a new account
- When the new account is created, I am notified that the account creation was successful

**Tasks**
- [ ] Install allauth and add to installed apps
- [ ] Add allauth urls
- [ ] Add signup link to navbar and to the home page
- [ ] Customise allauth signup form HTML template
- [ ] Create message to notify user of successfully creating a new account
